name: Atualizar EPG a cada 6 horas

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa às 00h, 06h, 12h, 18h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Baixar EPGs
        run: |
          curl -o epg.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/epg.xml
          curl -o claro.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/claro.xml
          curl -o globo.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/globo.xml
          curl -o vivoplay.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/vivoplay.xml

      - name: Gerar epg-final.xml sem canais e programmes duplicados
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > epg-final.xml
          echo '<!DOCTYPE tv SYSTEM "xmltv.dtd">' >> epg-final.xml
          echo '<tv generator-info-name="PAINEL UHD">' >> epg-final.xml

          touch canais_ids.txt

          for file in epg.xml claro.xml globo.xml vivoplay.xml; do
            # Adicionar canais únicos
            xmlstarlet sel -t -m "//channel" -c . -n "$file" | while read -r line; do
              channel_id=$(echo "$line" | xmlstarlet sel -t -v "//channel/@id" 2>/dev/null)
              if [ -n "$channel_id" ] && ! grep -q "^$channel_id$" canais_ids.txt; then
                echo "$line" >> epg-final.xml
                echo "$channel_id" >> canais_ids.txt
              fi
            done
          done

          # Adicionar os programmes apenas dos canais já adicionados
          for file in epg.xml claro.xml globo.xml vivoplay.xml; do
            xmlstarlet sel -t -m "//programme" -c . -n "$file" | while read -r prog; do
              channel_prog=$(echo "$prog" | xmlstarlet sel -t -v "//programme/@channel" 2>/dev/null)
              if [ -n "$channel_prog" ] && grep -q "^$channel_prog$" canais_ids.txt; then
                echo "$prog" >> epg-final.xml
              fi
            done
          done

          echo '</tv>' >> epg-final.xml

      - name: Commit e Push do EPG final
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add epg-final.xml
          git commit -m "EPG atualizado automaticamente"
          git push
