name: Atualizar EPG

on:
  schedule:
    # Roda a cada 6 horas nos horários terminados em 00 (ex: 00:00, 06:00, 12:00, 18:00)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Instalar xmlstarlet
      run: sudo apt-get update && sudo apt-get install -y xmlstarlet

    - name: Baixar arquivos XML
      run: |
        wget -O epg.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/epg.xml
        wget -O claro.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/claro.xml
        wget -O globo.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/globo.xml
        wget -O vivoplay.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/vivoplay.xml

    - name: Unir EPG removendo canais duplicados
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > epg-final.xml
        echo '<!DOCTYPE tv SYSTEM "xmltv.dtd">' >> epg-final.xml
        echo '<tv generator-info-name="PAINEL UHD">' >> epg-final.xml

        touch canais_ids.txt

        for file in epg.xml claro.xml globo.xml vivoplay.xml; do
          xmlstarlet sel -t -m "//channel" -c . -n "$file" | while IFS= read -r channel; do
            channel_id=$(echo "$channel" | xmlstarlet fo 2>/dev/null | xmlstarlet sel -t -v "//channel/@id" 2>/dev/null)
            if [ -n "$channel_id" ] && ! grep -Fxq "$channel_id" canais_ids.txt; then
              echo "$channel" >> epg-final.xml
              echo "$channel_id" >> canais_ids.txt
            fi
          done
        done

        for file in epg.xml claro.xml globo.xml vivoplay.xml; do
          xmlstarlet sel -t -m "//programme" -c . -n "$file" | while IFS= read -r prog; do
            channel_prog=$(echo "$prog" | xmlstarlet fo 2>/dev/null | xmlstarlet sel -t -v "//programme/@channel" 2>/dev/null)
            if [ -n "$channel_prog" ] && grep -Fxq "$channel_prog" canais_ids.txt; then
              echo "$prog" >> epg-final.xml
            fi
          done
        done

        echo '</tv>' >> epg-final.xml

        rm canais_ids.txt

    - name: Commitar e enviar epg-final.xml atualizado
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add epg-final.xml
        if git diff --cached --quiet; then
          echo "Nenhuma mudança no epg-final.xml"
        else
          git commit -m "Atualizar epg-final.xml automaticamente"
          git push
        fi
