name: Gerar EPG Final Sem Canais Duplicados

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas, nos minutos 00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Baixar os arquivos EPG
        run: |
          curl -L -o epg.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/epg.xml
          curl -L -o claro.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/claro.xml
          curl -L -o globo.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/globo.xml
          curl -L -o vivoplay.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/vivoplay.xml

      - name: Gerar epg-final.xml sem canais duplicados
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > epg-final.xml
          echo '<!DOCTYPE tv SYSTEM "xmltv.dtd">' >> epg-final.xml
          echo '<tv generator-info-name="PAINEL UHD">' >> epg-final.xml

          touch canais_ids.txt

          # Parte 1: Adicionar canais únicos
          for file in epg.xml claro.xml globo.xml vivoplay.xml; do
            xmlstarlet sel -t -m "//channel" -v "@id" -n "$file" | while IFS= read -r id; do
              if [ -n "$id" ] && ! grep -Fxq "$id" canais_ids.txt; then
                xmlstarlet sel -t -m "//channel[@id='$id']" -c . -n "$file" >> epg-final.xml
                echo "$id" >> canais_ids.txt
              fi
            done
          done

          # Parte 2: Adicionar programmes apenas dos canais únicos
          for file in epg.xml claro.xml globo.xml vivoplay.xml; do
            xmlstarlet sel -t -m "//programme" -v "@channel" -n "$file" | sort -u | while IFS= read -r channel; do
              if grep -Fxq "$channel" canais_ids.txt; then
                xmlstarlet sel -t -m "//programme[@channel='$channel']" -c . -n "$file" >> epg-final.xml
              fi
            done
          done

          echo '</tv>' >> epg-final.xml
          rm canais_ids.txt

      - name: Commit e push do epg-final.xml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add epg-final.xml
          git commit -m "EPG Final gerado automaticamente (sem canais duplicados)" || echo "Nenhuma alteração para commitar"
          git push
