name: Atualizar EPG merge diário

on:
  schedule:
    # A cada 6 horas: 0,6,12,18
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  merge-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Instalar xmlstarlet
      run: sudo apt-get update && sudo apt-get install -y xmlstarlet

    - name: Baixar arquivos XML EPG
      run: |
        curl -sLo epg.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/epg.xml
        curl -sLo claro.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/claro.xml
        curl -sLo globo.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/globo.xml
        curl -sLo vivoplay.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/vivoplay.xml

    - name: Merge XML EPG sem canais duplicados
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > epg-final.xml
        echo '<!DOCTYPE tv SYSTEM "xmltv.dtd">' >> epg-final.xml
        echo '<tv generator-info-name="PAINEL UHD">' >> epg-final.xml

        touch canais_ids.txt

        for file in epg.xml claro.xml globo.xml vivoplay.xml; do
          ids=$(xmlstarlet sel -t -m "//channel" -v "@id" -n "$file")
          for id in $ids; do
            if ! grep -Fxq "$id" canais_ids.txt; then
              xmlstarlet sel -t -m "//channel[@id='$id']" -c . -n "$file" >> epg-final.xml
              echo "$id" >> canais_ids.txt
            fi
          done
        done

        for file in epg.xml claro.xml globo.xml vivoplay.xml; do
          xmlstarlet sel -t -m "//programme[@channel]" -v "@channel" -n "$file" | sort -u | while read -r ch; do
            if grep -Fxq "$ch" canais_ids.txt; then
              xmlstarlet sel -t -m "//programme[@channel='$ch']" -c . -n "$file" >> epg-final.xml
            fi
          done
        done

        echo '</tv>' >> epg-final.xml

        rm canais_ids.txt

    - name: Commit e push do arquivo atualizado
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add epg-final.xml
        git commit -m "Atualização diária do EPG merge sem canais duplicados"
        git push
      continue-on-error: true
