name: Gerar EPG Final Sem Canais Duplicados

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Baixar os arquivos EPG
        run: |
          curl -L -o epg.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/epg.xml
          curl -L -o claro.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/claro.xml
          curl -L -o globo.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/globo.xml
          curl -L -o vivoplay.xml https://raw.githubusercontent.com/limaalef/BrazilTVEPG/main/vivoplay.xml

      - name: Gerar epg-final.xml sem canais duplicados
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > epg-final.xml
          echo '<!DOCTYPE tv SYSTEM "xmltv.dtd">' >> epg-final.xml
          echo '<tv generator-info-name="PAINEL UHD">' >> epg-final.xml

          touch canais_ids.txt

          # Parte 1: Adicionar canais únicos
          for file in epg.xml claro.xml globo.xml vivoplay.xml; do
            xmlstarlet sel -t -m "//channel" -v "@id" -n "$file" | while IFS= read -r id; do
              if [ -n "$id" ] && ! grep -Fxq "$id" canais_ids.txt; then
                # Só tenta extrair se existir
                if xmlstarlet sel -t -c "//channel[@id='$id']" "$file" > temp_channel.xml 2>/dev/null; then
                  cat temp_channel.xml >> epg-final.xml
                  echo "" >> epg-final.xml
                  echo "$id" >> canais_ids.txt
                fi
              fi
            done
          done

          # Parte 2: Adicionar programmes apenas dos canais únicos
          for file in epg.xml claro.xml globo.xml vivoplay.xml; do
            xmlstarlet sel -t -m "//programme" -v "@channel" -n "$file" | sort -u | while IFS= read -r channel; do
              if grep -Fxq "$channel" canais_ids.txt; then
                if xmlstarlet sel -t -c "//programme[@channel='$channel']" "$file" > temp_programme.xml 2>/dev/null; then
                  cat temp_programme.xml >> epg-final.xml
                  echo "" >> epg-final.xml
                fi
              fi
            done
          done

          echo '</tv>' >> epg-final.xml
          rm canais_ids.txt temp_channel.xml temp_programme.xml || true

      - name: Commit e Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add epg-final.xml
          git commit -m "EPG Final atualizado sem canais duplicados" || echo "Nenhuma alteração"
          git push
